#! /bin/bash
#                         ____        __  _____ __         
#                        / __ \____  / /_/ __(_) /__  _____
#                       / / / / __ \/ __/ /_/ / / _ \/ ___/
#                      / /_/ / /_/ / /_/ __/ / /  __(__  ) 
#                     /_____/\____/\__/_/ /_/_/\___/____/  
#                                                          

set -o nounset
set -o errexit

RED='\033[0;31m'
NC='\033[0m'

function install_zsh {
    sudo dnf -y install zsh

    chsh -s $(which zsh)
    sudo chsh -s $(which zsh) root

    # Install oh-my-zsh
    sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"

    stow zsh
}

function install_delta {
    sudo dnf -y install git-delta
    stow delta
}
function install_i3 {
    sudo dnf -y install i3 xbacklight feh arandr lxappearance compton i3blocks
    stow i3
}

function install_tools {
    stow todo
    sudo dnf -y install ranger highlight atool w3m htop lnav direnv zoxide fzf ripgrep bat httpie exa
    stow tools
}

function install_nvm {
    PROFILE=/dev/null bash -c 'curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash'
    stow nvm
    source nvm/.zshrc.d/nvm.sh
    nvm install node
}

function install_node_tools {
  npm i -g gitmoji-cli

}

function install_tmux {
    sudo dnf -y install tmux xclip
    stow tmux
    echo -e "${RED} Edit ~/.zshrc 'plugins=' to add tmux ${NC}"
}

function install_conky {
    sudo dnf -y install conky
    stow conky
}

function install_themes {
    stow themes
}

function ask {
    local label=`echo ${1} | sed "s/_/ /g"`
    read -p "${label} (Y/N) ? [Default : $2] : " choice
    choice=${choice:-$2}
    if [[ ${choice} =~ ^[Yy]$ ]]; then
        eval $1
    fi
}

cd $HOME/dotfiles

sudo dnf -y install curl stow git

ask install_zsh Y
ask install_tools Y
ask install_nvm Y
ask install_node_tools Y
ask install_delta Y
ask install_i3 N
ask install_tmux N
ask install_conky N
ask install_themes N
